Remove xtend
substack/browser-launcher pull request #54
Opened 2021-05-23 14:14 UTC by jimmywarting

Also lowest node version to support Object.assign was 4, so i change the engine version to that in package.json

2021-05-24 16:26 UTC, bcomnes requested changes
Looks good, just revert the path import styles to their original form.

2021-05-24 16:26 UTC, bcomnes commented on lib/windows/index.js
> +exports.ie = exports['internet-explorer'] = require('./ie.js');
Please leave the path style as they are. This line as an example, but please revert that change on all of them.

2021-05-24 17:14 UTC, jimmywarting commented on lib/windows/index.js
> +exports.ie = exports['internet-explorer'] = require('./ie.js');
Okey, I can revert it - but first: are you sure? I think it's a footgun if you ever decide to sometime switch to ESM

Ryan Dahl (inventor of NodeJS) regrets this pattern

> https://youtu.be/M3BM9TB-8yA?t=8406 
> Regret: require("module") without the extension ".js" 
> * Needlessly less explicit. 
> * Not how browser javascript works. You cannot omit the ".js" in a script tag src attribute. 
> * The module loader has to query the file system at multiple locations trying to guess what the user intended.

2021-05-24 17:33 UTC, bcomnes commented on lib/windows/index.js
> +exports.ie = exports['internet-explorer'] = require('./ie.js');
Yes I'm sure.

Dahl had a good reason to revisit this with deno, however Node is a different case. Node ESM has no path to direct browser run without import rewrites (due to the use of short names and its module resolution algorithm), which has to handle this case because Node.js module resolution algorithm is frozen. 

Additionally, this module will never run in a browser (or any other JS env).

Furthermore, this module is in maintenance mode so minimizing code churn is a priority.

2021-05-24 17:43 UTC, jimmywarting commented on lib/windows/index.js
> +exports.ie = exports['internet-explorer'] = require('./ie.js');
Done

2021-05-25 17:48 UTC, bcomnes approved these changes

2021-05-25 17:48 UTC, merged

2021-05-25 17:50 UTC, jimmywarting commented
if you are going to do a major release anyway, how about removing mkdirp also?

2021-05-25 17:50 UTC, jimmywarting commented
node 10.12.0

got support for recursive mode

2021-05-25 18:53 UTC, bcomnes commented
mkdirp uses recursive fs.mkdir under the hood now.  if it ain't broke, or deprecated, let's just leave this ol' module alone.